exclude: "hashes/"
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v5.0.0
    hooks:
      - id: check-yaml
        language: python
      - id: check-json
        language: python
      - id: end-of-file-fixer
        language: python
      - id: trailing-whitespace
        language: python
      - id: check-docstring-first
        language: python
      - id: requirements-txt-fixer
        language: python
      - id: check-merge-conflict
        language: python
      - id: check-toml
        language: python
      - id: check-xml
        language: python
      - id: check-ast
        language: python
      - id: check-builtin-literals
        language: python
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"
  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos
        args: []
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
