name: generate-plots
on:
  workflow_call:
    inputs:
      map-name:
        type: string
        required: true
      python-version:
        type: number
        required: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  generate-plot-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            /*
            !/spread_gifs/
            !/spread_images/
          sparse-checkout-cone-mode: false
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --release
      - name: Retrieve map artifacts
        uses: actions/download-artifact@v5
        with:
          name: map-artifacts
      - name: Generate plot input
        run: |
          ls -l --block-size=M .
          RUSTFLAGS='-C target-cpu=native' cargo run --release -- nav-analysis ${{ inputs.map-name }} 2>&1
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ inputs.map-name }}
          path: results/*.json

  generate-plot-output:
    runs-on: ubuntu-latest
    needs: generate-plot-input
    permissions:
      contents: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - name: Retrieve map artifacts
        uses: actions/download-artifact@v5
        with:
          name: map-artifacts
      - name: Retrieve results
        uses: actions/download-artifact@v5
        with:
          name: results-${{ inputs.map-name }}
          path: results
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}
      - name: Generate plots
        run: |
          ls -l --block-size=M
          ls -l --block-size=M results
          uv run -q --no-project --with tqdm --with matplotlib --with numpy --with pillow scripts/plot_spread.py ${{ inputs.map-name }}
      - uses: FedericoCarboni/setup-ffmpeg@v3.1
        id: setup-ffmpeg

      - name: Make script executable
        run: chmod +x scripts/generate_gif.sh

      - name: Generate GIF
        run: |
          ./scripts/generate_gif.sh "${{ inputs.map-name }}"
          ls -l --block-size=M .
          ls -l --block-size=M webpage_data

      - name: Retrieve hash-artifacts
        uses: actions/download-artifact@v5
        with:
          name: hash-artifacts
          path: hashes

      - name: Upload gif
        uses: actions/upload-artifact@v4
        with:
          name: gif-${{ inputs.map-name }}
          path: |
            spread_gifs/

      - name: Commit regenerated files (with retry)
        run: |
          git config --global user.name  'Jan-Eric Nitschke'
          git config --global user.email 'JanEricNitschke@users.noreply.github.com'

          for i in {1..5}; do
            echo "=== attempt $i ==="

            # ------------------------------------------------------------------
            # (re)generate everything that depends on the current repository state
            uv run -q --no-project scripts/update_webpage_data.py

            # ------------------------------------------------------------------
            # stage *all* artefacts in one go
            git add \
              spread_images/${{ inputs.map-name }}/ \
              spread_gifs/${{ inputs.map-name }}/ \
              hashes/${{ inputs.map-name }}.txt \
              index.html
            git restore .
            git clean -fd


            # nothing changed? -> we are done
            if git diff --cached --quiet; then
              echo "No changes - done"
              exit 0
            fi

            # create the commit
            git commit -m "Update webpage assets for ${{ inputs.map-name }}"

            # ------------------------------------------------------------------
            # try to push
            if git push origin HEAD:main; then
              echo "Push succeeded"; break
            fi

            echo "Push rejected - repository moved, retrying…"

            # ------------------------------------------------------------------
            # undo just-created commit *but* keep its file changes in the WD
            git reset --mixed HEAD~1
            git restore index.html
            git stash -u

            # re-align with the new main branch
            git pull --rebase origin main
            git stash pop

            # loop and try again after a short pause
            sleep 5
          done
